[package]
name = "iris-source"
description = "Range oriented data sources for iris: file, mapped file, object store."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
