//! Grade this crate against the reference implementation.
//!
//! `conformance/btrblocks` holds a corpus generated by linking against the reference, asking it to
//! compress a column, and asking it to decode the result. Every case is three files: the compressed
//! column part, the values the reference got out of it, and which rows it said were present. That
//! directory's README says how it was made and what is in it.
//!
//! This reads the same parts and must produce the same answers, byte for byte. M5 says any
//! deviation is a bug in ours until proven otherwise, and this is where that is decided.
//!
//! Nothing here builds or runs the reference. The fixtures are committed, so a change to iris needs
//! no C++ toolchain and no network.
//!
//! # Cases that are not decoded yet
//!
//! Most of the corpus uses schemes this crate has not implemented. Skipping those quietly would let
//! the suite pass while covering almost nothing, so a case is skipped only if the crate says so
//! itself by returning `UnsupportedScheme`, and the count of skipped cases is printed and checked.
//! When a scheme lands, its cases stop being skipped without anyone editing a list, and the check on
//! the count is what makes that a change somebody has to look at.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use iris_btr::{Column, ColumnType, Error, Part, Presence, Strings};

/// Where the corpus lives.
fn corpus() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../conformance/btrblocks/fixtures")
}

/// One line of the manifest.
struct Case {
    name: String,
    column: ColumnType,
    rows: u32,
    scheme: String,
}

/// Reads the manifest the generator wrote.
fn cases() -> Vec<Case> {
    let manifest = std::fs::read_to_string(corpus().join("manifest.txt")).expect("the manifest");
    manifest
        .lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map(|line| {
            let mut fields = line.split('\t');
            let name = fields.next().expect("a case name").to_owned();
            let column = match fields.next().expect("a column type") {
                "integer" => ColumnType::Integer,
                "double" => ColumnType::Double,
                "string" => ColumnType::String,
                other => panic!("the manifest names a column type of {other}"),
            };
            let rows = fields
                .next()
                .expect("a row count")
                .parse()
                .expect("a row count");
            let scheme = fields.next().expect("a scheme").to_owned();
            Case {
                name,
                column,
                rows,
                scheme,
            }
        })
        .collect()
}

/// Reads one of a case's three files.
fn read(name: &str, extension: &str) -> Vec<u8> {
    let path = corpus().join(format!("{name}.{extension}"));
    std::fs::read(&path).unwrap_or_else(|error| panic!("reading {}: {error}", path.display()))
}

/// Writes decoded values in the canonical form the corpus is recorded in.
///
/// This mirrors `answer_for` in `conformance/btrblocks/generate.cpp` and has to keep mirroring it.
/// Two things it does are the reason the comparison means anything.
///
/// It zeroes the value of every null row. The reference leaves those slots holding whatever was in
/// the allocation, so comparing them would be comparing two allocators rather than two decoders.
///
/// It writes strings in the reference's own layout, with each offset counted from the start of the
/// offset array rather than from the start of the bytes. This crate hands back offsets into the
/// bytes, which is what a columnar reader wants, so the arithmetic to get from one to the other
/// happens here and not in the crate.
fn canonical(column: &Column, presence: &Presence, rows: u32) -> Vec<u8> {
    match column {
        Column::Integer(values) => fixed(values.iter().map(|value| value.to_le_bytes()), presence),
        Column::Double(values) => fixed(values.iter().map(|value| value.to_le_bytes()), presence),
        Column::Text(text) => text_bytes(text, presence, rows),
    }
}

/// The canonical form of a fixed width column.
fn fixed<const N: usize>(values: impl Iterator<Item = [u8; N]>, presence: &Presence) -> Vec<u8> {
    let mut out = Vec::new();
    for (row, value) in values.enumerate() {
        let row = u32::try_from(row).expect("a row index");
        if presence.present(row) {
            out.extend_from_slice(&value);
        } else {
            out.extend_from_slice(&[0; N]);
        }
    }
    out
}

/// The canonical form of a string column.
fn text_bytes(text: &Strings, presence: &Presence, rows: u32) -> Vec<u8> {
    let rows = usize::try_from(rows).expect("a row count");
    let header = (rows + 1) * 4;

    let mut offsets = Vec::with_capacity(header);
    let mut bytes = Vec::new();
    for row in 0..rows {
        let at = header + bytes.len();
        offsets.extend_from_slice(&u32::try_from(at).expect("an offset").to_le_bytes());
        if presence.present(u32::try_from(row).expect("a row index")) {
            bytes.extend_from_slice(text.get(row).expect("a row"));
        }
    }
    let at = header + bytes.len();
    offsets.extend_from_slice(&u32::try_from(at).expect("an offset").to_le_bytes());

    offsets.extend_from_slice(&bytes);
    offsets
}

/// The nullmap in the form the corpus records it, one byte a row.
fn presence_bytes(presence: &Presence, rows: u32) -> Vec<u8> {
    (0..rows)
        .map(|row| u8::from(presence.present(row)))
        .collect()
}

#[test]
fn every_case_this_crate_decodes_matches_the_reference_byte_for_byte() {
    let mut waiting: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut decoded = 0;

    let cases = cases();
    assert!(
        !cases.is_empty(),
        "the corpus is empty, so this test proves nothing"
    );

    for case in &cases {
        let bytes = read(&case.name, "btr");
        let part = Part::parse(&bytes).unwrap_or_else(|error| panic!("{}: {error}", case.name));
        // Every case in the corpus is a single chunk column part. The framing carries a count, and
        // reading it rather than assuming one is what would catch a corpus that grew a case with
        // two.
        assert_eq!(
            part.chunks(),
            1,
            "{}: the corpus should hold single chunk parts",
            case.name
        );

        let chunk = part
            .chunk(0)
            .unwrap_or_else(|error| panic!("{}: {error}", case.name));
        assert_eq!(chunk.column(), case.column, "{}: column type", case.name);
        assert_eq!(chunk.rows(), case.rows, "{}: row count", case.name);

        let column = match chunk.decode() {
            Ok(column) => column,
            Err(error @ Error::UnsupportedScheme { .. }) => {
                waiting
                    .entry(format!("{error}"))
                    .or_default()
                    .push(case.name.clone());
                continue;
            }
            Err(error) => panic!("{}: {error}", case.name),
        };
        // Every nullmap encoding is read, so there is nothing here to be waiting on. An error from
        // this is a real one and fails the case rather than skipping it.
        let presence = chunk
            .nullmap()
            .presence()
            .unwrap_or_else(|error| panic!("{}: {error}", case.name));

        assert_eq!(
            presence_bytes(&presence, case.rows),
            read(&case.name, "null"),
            "{} ({}): the rows we call present are not the ones the reference does",
            case.name,
            case.scheme
        );

        let ours = canonical(&column, &presence, case.rows);
        let theirs = read(&case.name, "out");
        assert_eq!(
            ours.len(),
            theirs.len(),
            "{} ({}): we produced {} bytes and the reference produced {}",
            case.name,
            case.scheme,
            ours.len(),
            theirs.len()
        );
        if ours != theirs {
            let at = ours
                .iter()
                .zip(&theirs)
                .position(|(a, b)| a != b)
                .expect("a difference");
            panic!(
                "{} ({}): byte {at} is {:#04x} and the reference says {:#04x}",
                case.name, case.scheme, ours[at], theirs[at]
            );
        }
        decoded += 1;
    }

    // Printed rather than only counted, so that a run of this test says which schemes are still
    // missing without anybody going and reading the source to find out.
    for (reason, names) in &waiting {
        println!("waiting on {reason}: {}", names.join(", "));
    }
    println!("{decoded} of {} cases decoded", cases.len());

    // The floor is what stops this passing on a crate that decodes nothing. It goes up as schemes
    // land, and it is deliberately an inequality rather than an equality so that implementing a
    // scheme does not fail the suite that was asking for it.
    assert!(
        decoded >= 20,
        "only {decoded} cases decoded, which is fewer than the schemes already implemented cover"
    );
}

#[test]
fn the_corpus_is_the_one_the_generator_wrote() {
    // The manifest is the only place recording which scheme each case really came out as, and it is
    // written by the same run that writes the fixtures. Checking that every case it names has all
    // three of its files is what catches a corpus half copied out of a build machine.
    for case in cases() {
        for extension in ["btr", "out", "null"] {
            let path = corpus().join(format!("{}.{extension}", case.name));
            assert!(
                path.exists(),
                "{} is named in the manifest but {} is missing",
                case.name,
                path.display()
            );
        }
        assert_eq!(
            read(&case.name, "null").len(),
            usize::try_from(case.rows).expect("a row count"),
            "{}: the nullmap should hold one byte a row",
            case.name
        );
    }
}

#[test]
fn the_corpus_covers_every_scheme_the_reference_chooses_by_default() {
    // The corpus is only worth what it covers, and what it covers is decided by the generator
    // rather than here, so this is the check that the two have not drifted apart. A scheme dropping
    // out of the corpus is otherwise invisible: the suite goes on passing, and it stops asking the
    // question the missing case was there to ask.
    let manifest = cases();
    let all: String = manifest
        .iter()
        .map(|case| case.scheme.as_str())
        .collect::<Vec<_>>()
        .join(" ");

    for scheme in [
        "UNCOMPRESSED",
        "ONE_VALUE",
        "DICT",
        "RLE",
        "PFOR",
        "BP",
        "FREQUENCY",
        "PSEUDODECIMAL",
        "FSST",
        "S_DICT_RAW",
    ] {
        assert!(all.contains(scheme), "no case in the corpus uses {scheme}");
    }
}
