//! A reader for the `BtrBlocks` column format.
//!
//! `BtrBlocks` is a columnar compression format from the paper of the same name, and the reference
//! implementation lives at github.com/maxi-k/btrblocks under the MIT licence. This crate reads what
//! that implementation writes. It does not write the format and has no plans to.
//!
//! The unit is a column part, which is what the reference produces for one column of one file: a
//! small header and then a run of compressed chunks. See [`Part`].
//!
//! # Byte identical is the whole gate
//!
//! M5 asks for a decoder that agrees with the reference across a conformance corpus, and says that
//! any deviation is a bug in ours until proven otherwise. That is a claim about agreeing with
//! somebody else's code, so it cannot be checked against a test we wrote. `conformance/btrblocks`
//! holds a corpus generated by linking against the reference and asking it both to compress a
//! column and to decode the result, and the test suite here reads the same compressed bytes and
//! compares against the same answers.
//!
//! The consequence for this crate is that a scheme is either right or absent. There is no partial
//! implementation that decodes most rows, because the corpus does not grade most rows.
//!
//! # What is implemented
//!
//! `UNCOMPRESSED` and `ONE_VALUE`, for all three column types, and the two nullmap encodings that
//! say the same thing about every row. That is the framing and the trivial cases: enough to get
//! from a part on disk to values in hand without any of the answer depending on a scheme being
//! right, so that everything after it is a scheme dropped into a frame that already works.
//!
//! Everything else returns [`Error::UnsupportedScheme`], which the conformance suite counts rather
//! than ignores, so the number of cases still waiting is a number the test prints.
//!
//! # Parsing is the untrusted path
//!
//! A part arrives from somewhere. Reading one must not panic, must not read out of bounds, and must
//! not allocate on the basis of a length field it has not checked. The crate forbids `unsafe`
//! outright, so out of bounds is a language guarantee. The other two are how the parser is written:
//! every count is checked against the bytes that are really present before it is used to reserve
//! anything, and every field that could run off the end returns [`Error::Overrun`] instead.

#![forbid(unsafe_code)]

mod column;
mod error;
mod nullmap;
mod part;
mod scheme;

pub use column::{Column, Strings};
pub use error::{Error, Result};
pub use nullmap::{Nullmap, Presence};
pub use part::{Chunk, ColumnType, Part};
pub use scheme::scheme_name;

/// The version of this crate, as reported by build metadata.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

#[cfg(test)]
mod tests {
    use super::*;

    /// A part holding one chunk, laid out the way the reference lays one out.
    fn part(scheme: u8, nullmap: u8, column: u8, rows: u32, data: &[u8], map: &[u8]) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&1u32.to_le_bytes());
        bytes.extend_from_slice(&16u32.to_le_bytes());
        // The reference aligns the first chunk to sixteen bytes and leaves the gap as it found it,
        // so this fills it with something that is not zero rather than with zeroes.
        bytes.extend_from_slice(&[0xab; 8]);
        bytes.extend_from_slice(&[scheme, nullmap, column, 0xcd]);
        bytes.extend_from_slice(
            &u32::try_from(data.len())
                .expect("a small chunk")
                .to_le_bytes(),
        );
        bytes.extend_from_slice(&rows.to_le_bytes());
        bytes.extend_from_slice(data);
        bytes.extend_from_slice(map);
        bytes
    }

    #[test]
    fn a_part_reports_its_chunks_and_a_chunk_reports_its_header() {
        let bytes = part(0, 0, 0, 2, &[1, 0, 0, 0, 2, 0, 0, 0], &[]);
        let part = Part::parse(&bytes).expect("a part");
        assert_eq!(part.chunks(), 1);

        let chunk = part.chunk(0).expect("a chunk");
        assert_eq!(chunk.column(), ColumnType::Integer);
        assert_eq!(chunk.scheme(), 0);
        assert_eq!(chunk.rows(), 2);
        assert_eq!(chunk.decode().expect("values"), Column::Integer(vec![1, 2]));
    }

    #[test]
    fn the_padding_byte_in_a_chunk_header_is_not_read() {
        // The reference's struct has a byte of padding it never writes, so it holds whatever was in
        // the buffer. A reader that checked it would pass wherever it happened to be zero and fail
        // everywhere else, which is the kind of bug that only shows up on somebody else's machine.
        let one = part(1, 0, 0, 3, &[7, 0, 0, 0], &[]);
        let mut other = one.clone();
        other[19] = 0;
        assert_ne!(one, other);

        for bytes in [one, other] {
            let part = Part::parse(&bytes).expect("a part");
            let chunk = part.chunk(0).expect("a chunk");
            assert_eq!(
                chunk.decode().expect("values"),
                Column::Integer(vec![7, 7, 7])
            );
        }
    }

    #[test]
    fn a_chunk_index_past_the_end_is_refused_rather_than_wrapped() {
        let bytes = part(1, 0, 1, 1, &0f64.to_le_bytes(), &[]);
        let part = Part::parse(&bytes).expect("a part");
        let error = part.chunk(1).unwrap_err();
        assert!(
            matches!(error, Error::NoSuchChunk { index: 1, count: 1 }),
            "{error}"
        );
    }

    #[test]
    fn a_chunk_count_larger_than_the_part_allocates_nothing() {
        // The count is the field a hostile part would reach for, so it is checked against the bytes
        // that are really there before anything is read or reserved.
        let mut bytes = u32::MAX.to_le_bytes().to_vec();
        bytes.extend_from_slice(&[0; 16]);
        let error = Part::parse(&bytes).unwrap_err();
        assert!(
            matches!(
                error,
                Error::Truncated {
                    what: "the offset table",
                    ..
                }
            ),
            "{error}"
        );
    }

    #[test]
    fn a_row_count_larger_than_the_chunk_is_refused() {
        let bytes = part(0, 0, 0, 1000, &[1, 0, 0, 0], &[]);
        let part = Part::parse(&bytes).expect("a part");
        let error = part.chunk(0).expect("a chunk").decode().unwrap_err();
        assert!(
            matches!(error, Error::Overrun { claimed: 4000, .. }),
            "{error}"
        );
    }

    #[test]
    fn a_scheme_that_is_not_written_yet_is_told_apart_from_one_that_does_not_exist() {
        // The difference matters to whoever reads the failure. One of these says the part is fine
        // and iris is behind, and the other says the part did not come from the reference.
        let behind = part(4, 0, 0, 1, &[0; 8], &[]);
        let error = Part::parse(&behind)
            .expect("a part")
            .chunk(0)
            .expect("a chunk")
            .decode()
            .unwrap_err();
        assert!(
            matches!(error, Error::UnsupportedScheme { code: 4, .. }),
            "{error}"
        );
        assert!(format!("{error}").contains("PFOR"), "{error}");

        let nonsense = part(200, 0, 0, 1, &[0; 8], &[]);
        let error = Part::parse(&nonsense)
            .expect("a part")
            .chunk(0)
            .expect("a chunk")
            .decode()
            .unwrap_err();
        assert!(
            matches!(error, Error::UnknownScheme { code: 200, .. }),
            "{error}"
        );
    }

    #[test]
    fn a_column_type_the_reference_never_writes_is_refused() {
        // Codes 3 through 7 are names in the reference's enum with nothing behind them.
        let bytes = part(0, 0, 4, 1, &[0; 8], &[]);
        let error = Part::parse(&bytes).expect("a part").chunk(0).unwrap_err();
        assert!(
            matches!(error, Error::UnknownColumnType { code: 4 }),
            "{error}"
        );
    }

    #[test]
    fn the_two_constant_nullmaps_are_read_and_the_roaring_ones_are_not_yet() {
        let all = part(1, 0, 0, 2, &[9, 0, 0, 0], &[]);
        let chunk = Part::parse(&all)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        assert_eq!(chunk.nullmap().presence().expect("presence"), Presence::All);

        let none = part(1, 1, 0, 2, &[9, 0, 0, 0], &[]);
        let chunk = Part::parse(&none)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        assert_eq!(
            chunk.nullmap().presence().expect("presence"),
            Presence::None
        );

        let scattered = part(1, 3, 0, 2, &[9, 0, 0, 0], &[0xff; 4]);
        let chunk = Part::parse(&scattered)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let error = chunk.nullmap().presence().unwrap_err();
        assert!(
            matches!(error, Error::UnsupportedNullmap { code: 3 }),
            "{error}"
        );
    }

    #[test]
    fn a_null_row_still_gets_whatever_the_scheme_wrote_there() {
        // The reference leaves the value slot of a null row holding whatever it held, and copying
        // that is the point rather than an oversight. Zeroing here would be this crate answering a
        // question the reference does not answer, and the conformance corpus would then be graded
        // against our idea of what a null row should look like.
        let bytes = part(1, 1, 0, 2, &[5, 0, 0, 0], &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        assert_eq!(
            chunk.nullmap().presence().expect("presence"),
            Presence::None
        );
        assert_eq!(chunk.decode().expect("values"), Column::Integer(vec![5, 5]));
    }

    #[test]
    fn an_uncompressed_string_column_rebases_its_offsets_onto_the_bytes() {
        // The reference measures a string's offset from the start of the offset array, so a reader
        // that took those offsets as they came would put every string past its own start by the
        // length of the array. Two rows means three slots, so the bytes begin at twelve.
        let mut data = 21u32.to_le_bytes().to_vec();
        for slot in [12u32, 15, 21] {
            data.extend_from_slice(&slot.to_le_bytes());
        }
        data.extend_from_slice(b"abcdefghi");

        let bytes = part(0, 0, 2, 2, &data, &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let Column::Text(text) = chunk.decode().expect("values") else {
            panic!("a string column")
        };
        assert_eq!(text.len(), 2);
        assert_eq!(text.offsets(), [0, 3, 9]);
        assert_eq!(text.get(0), Some(&b"abc"[..]));
        assert_eq!(text.get(1), Some(&b"defghi"[..]));
        assert_eq!(text.get(2), None);
    }

    #[test]
    fn a_string_offset_pointing_into_the_offset_array_is_refused() {
        let mut data = 21u32.to_le_bytes().to_vec();
        for slot in [4u32, 15, 21] {
            data.extend_from_slice(&slot.to_le_bytes());
        }
        data.extend_from_slice(b"abcdefghi");

        let bytes = part(0, 0, 2, 2, &data, &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let error = chunk.decode().unwrap_err();
        assert!(
            matches!(
                error,
                Error::Overrun {
                    what: "a string offset",
                    claimed: 4,
                    ..
                }
            ),
            "{error}"
        );
    }

    #[test]
    fn a_one_value_string_column_repeats_the_string_for_every_row() {
        let mut data = 3u32.to_le_bytes().to_vec();
        data.extend_from_slice(b"xyz");

        let bytes = part(1, 0, 2, 3, &data, &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let Column::Text(text) = chunk.decode().expect("values") else {
            panic!("a string column")
        };
        assert_eq!(text.len(), 3);
        assert_eq!(text.bytes(), b"xyzxyzxyz");
        assert_eq!(text.get(2), Some(&b"xyz"[..]));
    }

    #[test]
    fn an_empty_one_value_string_column_is_a_length_and_nothing_after_it() {
        // What the reference writes for a column with no present rows at all. There is no value to
        // store, so it stores a length of zero, and every row comes back as an empty string.
        let bytes = part(1, 1, 2, 4, &0u32.to_le_bytes(), &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let Column::Text(text) = chunk.decode().expect("values") else {
            panic!("a string column")
        };
        assert_eq!(text.len(), 4);
        assert_eq!(text.offsets(), [0, 0, 0, 0, 0]);
        assert!(text.bytes().is_empty());
    }

    #[test]
    fn a_scheme_name_is_given_for_the_legacy_codes_the_reference_no_longer_picks() {
        // A part written by an older copy of the reference can carry one of these, and a reader
        // that met one should be able to say what it is rather than say a number.
        assert_eq!(scheme_name(ColumnType::Integer, 28), "TRUNCATION_8");
        assert_eq!(scheme_name(ColumnType::Double, 28), "DOUBLE_BP");
        assert_eq!(scheme_name(ColumnType::String, 3), "FSST");
        assert_eq!(scheme_name(ColumnType::String, 28), "unknown");
    }

    #[test]
    fn a_row_past_the_end_of_a_presence_map_is_not_present() {
        let each = Presence::Each(vec![true, false]);
        assert!(each.present(0));
        assert!(!each.present(1));
        assert!(!each.present(2));
    }
}
