//! A reader for the `BtrBlocks` column format.
//!
//! `BtrBlocks` is a columnar compression format from the paper of the same name, and the reference
//! implementation lives at github.com/maxi-k/btrblocks under the MIT licence. This crate reads what
//! that implementation writes. It does not write the format and has no plans to.
//!
//! The unit is a column part, which is what the reference produces for one column of one file: a
//! small header and then a run of compressed chunks. See [`Part`].
//!
//! # Byte identical is the whole gate
//!
//! M5 asks for a decoder that agrees with the reference across a conformance corpus, and says that
//! any deviation is a bug in ours until proven otherwise. That is a claim about agreeing with
//! somebody else's code, so it cannot be checked against a test we wrote. `conformance/btrblocks`
//! holds a corpus generated by linking against the reference and asking it both to compress a
//! column and to decode the result, and the test suite here reads the same compressed bytes and
//! compares against the same answers.
//!
//! The consequence for this crate is that a scheme is either right or absent. There is no partial
//! implementation that decodes most rows, because the corpus does not grade most rows.
//!
//! # What is implemented
//!
//! Every nullmap encoding, which is two that say the same thing about every row and two that are a
//! Roaring bitmap of the rows that are the exception. On the value side, `UNCOMPRESSED` and
//! `ONE_VALUE` for all three column types, `BP` for integer columns, which is bit packing, and
//! `DICT` and `RLE` for integer and double columns.
//!
//! The order that landed in was the framing and the trivial schemes first, so that getting from a
//! part on disk to values in hand did not depend on any scheme being right, and then bit packing,
//! because most of the rest cascade through it: a dictionary stores its codes bit packed, a run
//! length encoding stores its values bit packed, and so on. Neither the packing nor the bitmap is
//! the reference's own format. The first is Daniel Lemire's `FastPFOR` and the second is
//! `CRoaring`, and the reference calls out to both and stores what they produced verbatim.
//!
//! Because schemes nest, decoding is written as a function per column type that takes a scheme code
//! and a byte slice, rather than as something hanging off a chunk. A nested scheme has no chunk
//! header around it, only a code recorded by whatever wrapped it.
//!
//! Everything else returns [`Error::UnsupportedScheme`], which the conformance suite counts rather
//! than ignores, so the number of cases still waiting is a number the test prints.
//!
//! # Parsing is the untrusted path
//!
//! A part arrives from somewhere. Reading one must not panic, must not read out of bounds, and must
//! not allocate on the basis of a length field it has not checked. The crate forbids `unsafe`
//! outright, so out of bounds is a language guarantee. The other two are how the parser is written:
//! every count is checked against the bytes that are really present before it is used to reserve
//! anything, and every field that could run off the end returns [`Error::Overrun`] instead.

#![forbid(unsafe_code)]

mod column;
mod error;
mod fastpfor;
mod nullmap;
mod part;
mod roaring;
mod scheme;

pub use column::{Column, Strings};
pub use error::{Error, Result};
pub use nullmap::{Nullmap, Presence};
pub use part::{Chunk, ColumnType, Part};
pub use scheme::scheme_name;

/// The version of this crate, as reported by build metadata.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

#[cfg(test)]
mod tests {
    use super::*;

    /// A part holding one chunk, laid out the way the reference lays one out.
    fn part(scheme: u8, nullmap: u8, column: u8, rows: u32, data: &[u8], map: &[u8]) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&1u32.to_le_bytes());
        bytes.extend_from_slice(&16u32.to_le_bytes());
        // The reference aligns the first chunk to sixteen bytes and leaves the gap as it found it,
        // so this fills it with something that is not zero rather than with zeroes.
        bytes.extend_from_slice(&[0xab; 8]);
        bytes.extend_from_slice(&[scheme, nullmap, column, 0xcd]);
        bytes.extend_from_slice(
            &u32::try_from(data.len())
                .expect("a small chunk")
                .to_le_bytes(),
        );
        bytes.extend_from_slice(&rows.to_le_bytes());
        bytes.extend_from_slice(data);
        bytes.extend_from_slice(map);
        bytes
    }

    /// The bytes of a numeric dictionary chunk.
    ///
    /// A scheme byte for the codes, the offset the codes start at, the dictionary, then the codes.
    /// The offset is the length of the dictionary, which is the only thing that says how long it
    /// is, so it is written from `entries` rather than passed in.
    fn dictionary(codes: u8, entries: &[u8], packed: &[u8]) -> Vec<u8> {
        let mut bytes = vec![codes];
        bytes.extend_from_slice(
            &u32::try_from(entries.len())
                .expect("a small dictionary")
                .to_le_bytes(),
        );
        bytes.extend_from_slice(entries);
        bytes.extend_from_slice(packed);
        bytes
    }

    #[test]
    fn a_dictionary_column_looks_its_codes_up_in_its_own_entries() {
        // Codes held uncompressed, so this is about the dictionary and not about the packing.
        let entries: Vec<u8> = [10i32, 20, 30]
            .iter()
            .flat_map(|v| v.to_le_bytes())
            .collect();
        let codes: Vec<u8> = [2i32, 0, 1, 2]
            .iter()
            .flat_map(|v| v.to_le_bytes())
            .collect();
        let bytes = part(2, 0, 0, 4, &dictionary(0, &entries, &codes), &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert_eq!(
            part.chunk(0).expect("a chunk").decode().expect("values"),
            Column::Integer(vec![30, 10, 20, 30])
        );
    }

    #[test]
    fn a_dictionary_holds_doubles_in_exactly_the_same_shape() {
        // The reference writes one structure for both numeric types and changes only the width of
        // an entry, so the only thing that should differ here is the column type byte.
        let entries: Vec<u8> = [1.5f64, -0.25]
            .iter()
            .flat_map(|v| v.to_le_bytes())
            .collect();
        let codes: Vec<u8> = [1i32, 1, 0].iter().flat_map(|v| v.to_le_bytes()).collect();
        let bytes = part(2, 0, 1, 3, &dictionary(0, &entries, &codes), &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert_eq!(
            part.chunk(0).expect("a chunk").decode().expect("values"),
            Column::Double(vec![-0.25, -0.25, 1.5])
        );
    }

    #[test]
    fn a_code_pointing_outside_the_dictionary_is_refused() {
        // The reference indexes with the code directly, so a part like this reads whatever was next
        // in its address space and there is no answer to copy.
        let entries: Vec<u8> = [10i32, 20].iter().flat_map(|v| v.to_le_bytes()).collect();
        let codes: Vec<u8> = [0i32, 7].iter().flat_map(|v| v.to_le_bytes()).collect();
        let bytes = part(2, 0, 0, 2, &dictionary(0, &entries, &codes), &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert!(matches!(
            part.chunk(0).expect("a chunk").decode(),
            Err(Error::Malformed {
                what: "a dictionary",
                ..
            })
        ));
    }

    #[test]
    fn a_dictionary_whose_entries_do_not_divide_into_values_is_refused() {
        let bytes = part(
            2,
            0,
            0,
            1,
            &dictionary(0, &[1, 2, 3], &0i32.to_le_bytes()),
            &[],
        );
        let part = Part::parse(&bytes).expect("a part");
        assert!(matches!(
            part.chunk(0).expect("a chunk").decode(),
            Err(Error::Malformed {
                what: "a dictionary",
                ..
            })
        ));
    }

    /// The bytes of a run length encoded chunk.
    ///
    /// A run count, the offset the counts start at, a scheme byte for the values and one for the
    /// counts, then the values and then the counts. The offset is the length of the values, so it
    /// is written from them rather than passed in.
    fn runs(count: u32, values: &[u8], counts: &[u8]) -> Vec<u8> {
        let mut bytes = count.to_le_bytes().to_vec();
        bytes.extend_from_slice(
            &u32::try_from(values.len())
                .expect("a small run column")
                .to_le_bytes(),
        );
        // Both nested columns uncompressed, so these tests are about the runs and not about
        // whatever is under them.
        bytes.extend_from_slice(&[0, 0]);
        bytes.extend_from_slice(values);
        bytes.extend_from_slice(counts);
        bytes
    }

    /// A little endian integer column, which is what both halves of a run length encoding are.
    fn ints(values: &[i32]) -> Vec<u8> {
        values.iter().flat_map(|v| v.to_le_bytes()).collect()
    }

    #[test]
    fn a_run_length_encoded_column_repeats_each_value_its_run_length() {
        // A value that comes back twice is deliberate. The reference records a run per transition
        // rather than per distinct value, so the same value can hold two runs, and a reader that
        // decided otherwise would be right on this data for the wrong reason.
        let data = runs(3, &ints(&[7, -1, 7]), &ints(&[2, 3, 1]));
        let bytes = part(3, 0, 0, 6, &data, &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert_eq!(
            part.chunk(0).expect("a chunk").decode().expect("values"),
            Column::Integer(vec![7, 7, -1, -1, -1, 7])
        );
    }

    #[test]
    fn a_run_length_encoded_column_holds_doubles_with_the_counts_still_integers() {
        // The reference decodes both numeric types through one template, changing only the width of
        // a value, and the counts stay an integer column either way. So the only thing that differs
        // from the integer case is the column type byte and the width of what is in the values.
        let values: Vec<u8> = [1.5f64, -0.25]
            .iter()
            .flat_map(|v| v.to_le_bytes())
            .collect();
        let data = runs(2, &values, &ints(&[1, 2]));
        let bytes = part(3, 0, 1, 3, &data, &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert_eq!(
            part.chunk(0).expect("a chunk").decode().expect("values"),
            Column::Double(vec![1.5, -0.25, -0.25])
        );
    }

    #[test]
    fn runs_that_do_not_cover_every_row_are_refused() {
        // The reference would leave the rows past the last run holding whatever the allocation held,
        // so there is no answer here to match.
        let data = runs(1, &ints(&[4]), &ints(&[2]));
        let bytes = part(3, 0, 0, 5, &data, &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert!(matches!(
            part.chunk(0).expect("a chunk").decode(),
            Err(Error::Malformed {
                what: "a run length encoded column",
                why: "its runs do not cover every row of the chunk",
            })
        ));
    }

    #[test]
    fn runs_that_cover_more_rows_than_the_chunk_holds_are_refused() {
        // The reference writes a run straight into its output with no bound, so this is the part
        // shape that would run it off the end of its own allocation.
        let data = runs(1, &ints(&[4]), &ints(&[9]));
        let bytes = part(3, 0, 0, 2, &data, &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert!(matches!(
            part.chunk(0).expect("a chunk").decode(),
            Err(Error::Malformed {
                what: "a run length encoded column",
                why: "its runs cover more rows than the chunk holds",
            })
        ));
    }

    #[test]
    fn a_run_of_a_negative_number_of_rows_is_refused() {
        // Counts are an integer column and integers are signed, so a negative one is a shape the
        // format allows and the reference would take backwards.
        let data = runs(1, &ints(&[4]), &ints(&[-1]));
        let bytes = part(3, 0, 0, 1, &data, &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert!(matches!(
            part.chunk(0).expect("a chunk").decode(),
            Err(Error::Malformed {
                what: "a run length encoded column",
                why: "a run is a negative number of rows long",
            })
        ));
    }

    #[test]
    fn more_runs_than_the_chunk_has_rows_is_refused_before_anything_is_decoded() {
        // A run covers at least one row, so this cannot describe a real column. The run count is
        // what the two nested columns get asked for, so it is checked before either of them is read
        // and the values here are deliberately not there at all.
        let data = runs(4000, &[], &[]);
        let bytes = part(3, 0, 0, 2, &data, &[]);

        let part = Part::parse(&bytes).expect("a part");
        assert!(matches!(
            part.chunk(0).expect("a chunk").decode(),
            Err(Error::Malformed {
                what: "a run length encoded column",
                why: "it has more runs than the chunk has rows",
            })
        ));
    }

    #[test]
    fn a_cascade_that_nests_forever_is_refused_rather_than_taking_the_stack() {
        // Each layer is a dictionary whose codes are another dictionary. The reference caps a
        // cascade at three and nothing it writes is deeper, so a part shaped like this did not come
        // from it, and the only question is whether reading it returns or takes the process with it.
        let mut data = dictionary(0, &0i32.to_le_bytes(), &0i32.to_le_bytes());
        for _ in 0..12 {
            data = dictionary(2, &0i32.to_le_bytes(), &data);
        }

        let bytes = part(2, 0, 0, 1, &data, &[]);
        let part = Part::parse(&bytes).expect("a part");
        assert!(matches!(
            part.chunk(0).expect("a chunk").decode(),
            Err(Error::Malformed {
                what: "a cascade of schemes",
                ..
            })
        ));
    }

    #[test]
    fn a_part_reports_its_chunks_and_a_chunk_reports_its_header() {
        let bytes = part(0, 0, 0, 2, &[1, 0, 0, 0, 2, 0, 0, 0], &[]);
        let part = Part::parse(&bytes).expect("a part");
        assert_eq!(part.chunks(), 1);

        let chunk = part.chunk(0).expect("a chunk");
        assert_eq!(chunk.column(), ColumnType::Integer);
        assert_eq!(chunk.scheme(), 0);
        assert_eq!(chunk.rows(), 2);
        assert_eq!(chunk.decode().expect("values"), Column::Integer(vec![1, 2]));
    }

    #[test]
    fn the_padding_byte_in_a_chunk_header_is_not_read() {
        // The reference's struct has a byte of padding it never writes, so it holds whatever was in
        // the buffer. A reader that checked it would pass wherever it happened to be zero and fail
        // everywhere else, which is the kind of bug that only shows up on somebody else's machine.
        let one = part(1, 0, 0, 3, &[7, 0, 0, 0], &[]);
        let mut other = one.clone();
        other[19] = 0;
        assert_ne!(one, other);

        for bytes in [one, other] {
            let part = Part::parse(&bytes).expect("a part");
            let chunk = part.chunk(0).expect("a chunk");
            assert_eq!(
                chunk.decode().expect("values"),
                Column::Integer(vec![7, 7, 7])
            );
        }
    }

    #[test]
    fn a_chunk_index_past_the_end_is_refused_rather_than_wrapped() {
        let bytes = part(1, 0, 1, 1, &0f64.to_le_bytes(), &[]);
        let part = Part::parse(&bytes).expect("a part");
        let error = part.chunk(1).unwrap_err();
        assert!(
            matches!(error, Error::NoSuchChunk { index: 1, count: 1 }),
            "{error}"
        );
    }

    #[test]
    fn a_chunk_count_larger_than_the_part_allocates_nothing() {
        // The count is the field a hostile part would reach for, so it is checked against the bytes
        // that are really there before anything is read or reserved.
        let mut bytes = u32::MAX.to_le_bytes().to_vec();
        bytes.extend_from_slice(&[0; 16]);
        let error = Part::parse(&bytes).unwrap_err();
        assert!(
            matches!(
                error,
                Error::Truncated {
                    what: "the offset table",
                    ..
                }
            ),
            "{error}"
        );
    }

    #[test]
    fn a_row_count_larger_than_the_chunk_is_refused() {
        let bytes = part(0, 0, 0, 1000, &[1, 0, 0, 0], &[]);
        let part = Part::parse(&bytes).expect("a part");
        let error = part.chunk(0).expect("a chunk").decode().unwrap_err();
        assert!(
            matches!(error, Error::Overrun { claimed: 4000, .. }),
            "{error}"
        );
    }

    #[test]
    fn a_scheme_that_is_not_written_yet_is_told_apart_from_one_that_does_not_exist() {
        // The difference matters to whoever reads the failure. One of these says the part is fine
        // and iris is behind, and the other says the part did not come from the reference.
        let behind = part(4, 0, 0, 1, &[0; 8], &[]);
        let error = Part::parse(&behind)
            .expect("a part")
            .chunk(0)
            .expect("a chunk")
            .decode()
            .unwrap_err();
        assert!(
            matches!(error, Error::UnsupportedScheme { code: 4, .. }),
            "{error}"
        );
        assert!(format!("{error}").contains("PFOR"), "{error}");

        let nonsense = part(200, 0, 0, 1, &[0; 8], &[]);
        let error = Part::parse(&nonsense)
            .expect("a part")
            .chunk(0)
            .expect("a chunk")
            .decode()
            .unwrap_err();
        assert!(
            matches!(error, Error::UnknownScheme { code: 200, .. }),
            "{error}"
        );
    }

    #[test]
    fn a_column_type_the_reference_never_writes_is_refused() {
        // Codes 3 through 7 are names in the reference's enum with nothing behind them.
        let bytes = part(0, 0, 4, 1, &[0; 8], &[]);
        let error = Part::parse(&bytes).expect("a part").chunk(0).unwrap_err();
        assert!(
            matches!(error, Error::UnknownColumnType { code: 4 }),
            "{error}"
        );
    }

    #[test]
    fn all_four_nullmap_encodings_are_read() {
        let all = part(1, 0, 0, 2, &[9, 0, 0, 0], &[]);
        let chunk = Part::parse(&all)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        assert_eq!(chunk.nullmap().presence().expect("presence"), Presence::All);

        let none = part(1, 1, 0, 2, &[9, 0, 0, 0], &[]);
        let chunk = Part::parse(&none)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        assert_eq!(
            chunk.nullmap().presence().expect("presence"),
            Presence::None
        );

        // The same bitmap under both scattered encodings, holding row one and nothing else. Under
        // the regular one that is the row that is present, and under the flipped one it is the row
        // that is null, so the two answers have to come out opposite.
        let mut map = vec![1u8];
        map.extend_from_slice(&1u32.to_le_bytes());
        map.extend_from_slice(&1u32.to_le_bytes());

        let regular = part(1, 2, 0, 2, &[9, 0, 0, 0], &map);
        let chunk = Part::parse(&regular)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        assert_eq!(
            chunk.nullmap().presence().expect("presence"),
            Presence::Each(vec![false, true])
        );

        let flipped = part(1, 3, 0, 2, &[9, 0, 0, 0], &map);
        let chunk = Part::parse(&flipped)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        assert_eq!(
            chunk.nullmap().presence().expect("presence"),
            Presence::Each(vec![true, false])
        );
    }

    #[test]
    fn a_null_row_still_gets_whatever_the_scheme_wrote_there() {
        // The reference leaves the value slot of a null row holding whatever it held, and copying
        // that is the point rather than an oversight. Zeroing here would be this crate answering a
        // question the reference does not answer, and the conformance corpus would then be graded
        // against our idea of what a null row should look like.
        let bytes = part(1, 1, 0, 2, &[5, 0, 0, 0], &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        assert_eq!(
            chunk.nullmap().presence().expect("presence"),
            Presence::None
        );
        assert_eq!(chunk.decode().expect("values"), Column::Integer(vec![5, 5]));
    }

    #[test]
    fn an_uncompressed_string_column_rebases_its_offsets_onto_the_bytes() {
        // The reference measures a string's offset from the start of the offset array, so a reader
        // that took those offsets as they came would put every string past its own start by the
        // length of the array. Two rows means three slots, so the bytes begin at twelve.
        let mut data = 21u32.to_le_bytes().to_vec();
        for slot in [12u32, 15, 21] {
            data.extend_from_slice(&slot.to_le_bytes());
        }
        data.extend_from_slice(b"abcdefghi");

        let bytes = part(0, 0, 2, 2, &data, &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let Column::Text(text) = chunk.decode().expect("values") else {
            panic!("a string column")
        };
        assert_eq!(text.len(), 2);
        assert_eq!(text.offsets(), [0, 3, 9]);
        assert_eq!(text.get(0), Some(&b"abc"[..]));
        assert_eq!(text.get(1), Some(&b"defghi"[..]));
        assert_eq!(text.get(2), None);
    }

    #[test]
    fn a_string_offset_pointing_into_the_offset_array_is_refused() {
        let mut data = 21u32.to_le_bytes().to_vec();
        for slot in [4u32, 15, 21] {
            data.extend_from_slice(&slot.to_le_bytes());
        }
        data.extend_from_slice(b"abcdefghi");

        let bytes = part(0, 0, 2, 2, &data, &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let error = chunk.decode().unwrap_err();
        assert!(
            matches!(
                error,
                Error::Overrun {
                    what: "a string offset",
                    claimed: 4,
                    ..
                }
            ),
            "{error}"
        );
    }

    #[test]
    fn a_one_value_string_column_repeats_the_string_for_every_row() {
        let mut data = 3u32.to_le_bytes().to_vec();
        data.extend_from_slice(b"xyz");

        let bytes = part(1, 0, 2, 3, &data, &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let Column::Text(text) = chunk.decode().expect("values") else {
            panic!("a string column")
        };
        assert_eq!(text.len(), 3);
        assert_eq!(text.bytes(), b"xyzxyzxyz");
        assert_eq!(text.get(2), Some(&b"xyz"[..]));
    }

    #[test]
    fn an_empty_one_value_string_column_is_a_length_and_nothing_after_it() {
        // What the reference writes for a column with no present rows at all. There is no value to
        // store, so it stores a length of zero, and every row comes back as an empty string.
        let bytes = part(1, 1, 2, 4, &0u32.to_le_bytes(), &[]);
        let chunk = Part::parse(&bytes)
            .expect("a part")
            .chunk(0)
            .expect("a chunk");
        let Column::Text(text) = chunk.decode().expect("values") else {
            panic!("a string column")
        };
        assert_eq!(text.len(), 4);
        assert_eq!(text.offsets(), [0, 0, 0, 0, 0]);
        assert!(text.bytes().is_empty());
    }

    #[test]
    fn a_scheme_name_is_given_for_the_legacy_codes_the_reference_no_longer_picks() {
        // A part written by an older copy of the reference can carry one of these, and a reader
        // that met one should be able to say what it is rather than say a number.
        assert_eq!(scheme_name(ColumnType::Integer, 28), "TRUNCATION_8");
        assert_eq!(scheme_name(ColumnType::Double, 28), "DOUBLE_BP");
        assert_eq!(scheme_name(ColumnType::String, 3), "FSST");
        assert_eq!(scheme_name(ColumnType::String, 28), "unknown");
    }

    #[test]
    fn a_row_past_the_end_of_a_presence_map_is_not_present() {
        let each = Presence::Each(vec![true, false]);
        assert!(each.present(0));
        assert!(!each.present(1));
        assert!(!each.present(2));
    }
}
